backend:
  name: github
  repo: swarmlabel721-create/creature-works
  branch: main

media_folder: "images"
public_folder: "/images"

locale: 'ja'

collections:
  - name: "blog"
    label: "ブログ記事"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "公開日", name: "date", widget: "datetime", format: "YYYY.MM.DD" }
      - { label: "カテゴリ", name: "category", widget: "select", options: ["MAKING", "GRAFFITI", "3D PRINT", "EVENT", "INFO"] }
      - { label: "サムネイル画像", name: "thumbnail", widget: "image", required: false }
      - { label: "抜粋", name: "excerpt", widget: "text" }
      - { label: "本文", name: "body", widget: "markdown" }
      - { label: "FEATURED", name: "featured", widget: "boolean", default: false }
